sonar.organization=vechain
sonar.projectKey=vechain_b3tr
sonar.verbose=false
sonar.sources= apps/frontend/
sonar.tests= apps/frontend/test/
sonar.test.inclusions= apps/frontend/test/**/*
sonar.cpd.exclusions= apps/frontend/test/**/*
sonar.javascript.lcov.reportPaths=apps/frontend/coverage/**/lcov.info
