/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/vevote/proposal/results": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Returns a list of results on vote weight per support */
    get: operations["getResults"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/vevote/historic-proposals": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Fetch all historic proposals */
    get: operations["getAllProposals"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/vevote/historical_proposals": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Fetch all historic proposals */
    get: operations["getAllProposals_1"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/transfers": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get transfer events by address or token address */
    get: operations["getTransferEvents"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/transfers/to": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get transfer events by to address */
    get: operations["getTransferEventsByTo"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/transfers/fungible-tokens-contracts": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get all fungible tokens transfers contracts for a given account */
    get: operations["getFungibleTokensContractsByAddress"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/transfers/from": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get transfer events by from address */
    get: operations["getTransferEventsByFrom"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/transfers/forBlock": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get transfer events for a specific block */
    get: operations["getTransfersForBlock"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/transactions": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get all transactions by an origin or delegator address */
    get: operations["getTransactionsByOriginOrDelegator"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/transactions/{txId}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get transaction by ID */
    get: operations["getTransactionById"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/transactions/delegated": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get all delegated transactions by a delegator address */
    get: operations["getDelegatedTransactions"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/transactions/contract": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get all transactions for a contract address */
    get: operations["getTransactionsByContract"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/stargate/total-vtho-claimed": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get total VTHO claimed by Stargate users */
    get: operations["getTotalVthoClaimed"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/stargate/total-vtho-claimed/{account}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get total VTHO claimed by a given account */
    get: operations["getTotalVthoClaimed_1"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/stargate/total-vtho-claimed/historic/{range}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get historic data for total VTHO claimed
     * @description This endpoint returns a time series of total VTHO claimed by all Stargate users.
     */
    get: operations["getTotalVthoClaimed_2"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/stargate/total-vet-staked": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get total VET staked in Stargate */
    get: operations["getTotalVetStaked"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/stargate/total-vet-staked/historic/{range}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get historic data for total VET staked
     * @description This endpoint returns a time series of total VET staked in Stargate. The time series is sparsely populated, so it may not contain consistent gaps between records.
     */
    get: operations["getTotalVetStaked_1"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/stargate/nft-holders": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get total number of NFT holders in Stargate */
    get: operations["getNftHolders"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/stargate/nft-holders/historic/{range}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get historic data for total NFT holders
     * @description This endpoint returns a time series of NFT holders in Stargate. The time series is sparsely populated, so it may not contain consistent gaps between records.
     */
    get: operations["getNftHolders_1"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/nfts": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get all NFTs owned by an address */
    get: operations["getOwnedNFTs"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/nfts/contracts": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get all contracts addresses by NFT owner */
    get: operations["getContractsByNFTOwner"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/history/{account}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get account history */
    get: operations["getUsersHistory"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/b3tr/xallocations/{roundId}/results": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get the results of XAllocation voting for a specific round. */
    get: operations["getAllocationVoteResults"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/b3tr/users/{wallet}/proposals/comments": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get the comments made by a user on proposals. */
    get: operations["getUserProposalComments"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/b3tr/proposals/{proposalId}/results": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get the results of a proposal. */
    get: operations["getProposalResult"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/b3tr/proposals/{proposalId}/comments": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get the comments for a proposal. */
    get: operations["getProposalComments"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/b3tr/galaxy-members/level-overview": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get B3TR GM Level UserAllTimeActionSummary
     * @description Returns the current overview (holders, B3TR donated, etc.) for each Galaxy Member level.
     */
    get: operations["getLevelOverviews"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/b3tr/actions/users/{wallet}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get B3TR actions for a user */
    get: operations["getUserActions"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/b3tr/actions/users/{wallet}/overview": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get B3TR action overview for a specific wallet, optionally for a specific round or date.
     * @description
     *                 This endpoint retrieves the B3TR action overview for a wallet address.
     *                 Optionally, a roundId or a date can be provided to retrieve the overview for a specific round or date.
     *
     *                 - If roundId is provided, the overview for the specific round is returned.
     *                 - If date is provided, the overview for the specific date is returned.
     *                 - If roundId/date are not provided, the all time sustainability overview for the user is returned.
     *                 - If both roundId and date are provided, a BadRequest error is returned.
     *
     */
    get: operations["getUserOverview"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/b3tr/actions/users/{wallet}/daily-summaries": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get daily action summaries for a specific user within a specified range. */
    get: operations["getDailySummariesForRange"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/b3tr/actions/leaderboards/users": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get leaderboard of user's B3TR actions.
     * @description
     *                 This endpoint retrieves the user leaderboard based on their B3TR actions.
     *
     *                 - If roundId is provided, the leaderboard for the specific round is returned.
     *                 - If date is provided, the leaderboard for the specific date is returned.
     *                 - If neither roundId nor date are provided, the all-time leaderboard is returned.
     *                 - If both roundId and date are provided, a BadRequest error is returned.
     *
     *
     */
    get: operations["getUserLeaderboard"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/b3tr/actions/leaderboards/apps": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get the app B3TR action leaderboard
     * @description
     *                 This endpoint retrieves the app B3TR action leaderboard.
     *
     *                 - If roundId is provided, the leaderboard for the specific round is returned.
     *                 - If date is provided, the leaderboard for the specific date is returned.
     *                 - If neither roundId nor date are provided, the all-time leaderboard is returned.
     *                 - If both roundId and date are provided, a BadRequest error is returned.
     *
     *
     */
    get: operations["getAppLeaderboard"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/b3tr/actions/leaderboards/apps/{appId}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get the user B3TR action leaderboard for a given app
     * @description
     *                 This endpoint retrieves the user B3TR action leaderboard for a given app.
     *
     *                 - If roundId is provided, the leaderboard for the specific round is returned.
     *                 - If date is provided, the leaderboard for the specific date is returned.
     *                 - If neither roundId nor date are provided, the all-time leaderboard is returned.
     *                 - If both roundId and date are provided, a BadRequest error is returned.
     *
     *
     */
    get: operations["getUserAppLeaderboard"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/b3tr/actions/global/overview": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get global B3TR action overview, optionally for a specific round or date.
     * @description
     *                 This endpoint retrieves the global B3TR action overview.
     *                 Optionally, a roundId or a date can be provided to retrieve the overview for a specific round or date.
     *                 - If roundId is provided, the overview for the specific round is returned.
     *                 - If date is provided, the overview for the specific date is returned.
     *                 - If roundId/date are not provided, the all time global sustainability overview is returned.
     *                 - If both roundId and date are provided, a BadRequest error is returned.
     *
     */
    get: operations["getGlobalOverview"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/b3tr/actions/apps/{appId}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get B3TR actions for an app */
    get: operations["getAppActions"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/b3tr/actions/apps/{appId}/overview": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get B3TR action overview for a specific app, optionally for a specific round or date.
     * @description
     *                 This endpoint retrieves the B3TR action overview for an app.
     *                 Optionally, a roundId or a date can be provided to retrieve the overview for a specific round or date.
     *
     *                 - If roundId is provided, the overview for the specific round is returned.
     *                 - If date is provided, the overview for the specific date is returned.
     *                 - If roundId/date are not provided, the all time sustainability overview for the app is returned.
     *                 - If both roundId and date are provided, a BadRequest error is returned.
     *
     */
    get: operations["getAppOverview"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/authority_endorsers/endorsers/{user}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Check if a user is an endorser of any Authority Master Node. */
    get: operations["checkUserIsEndorser"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/authority-endorsers/endorsers/{user}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Check if a user is an endorser of any Authority Master Node. */
    get: operations["checkUserIsEndorser_1"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    ExceptionResponse: {
      id: string
      /** Format: int32 */
      status: number
      message?: string
      error: string
      path: string
      timestamp: number
    }
    PaginatedResponseVeVoteProposalResult: {
      data: components["schemas"]["VeVoteProposalResult"][]
      pagination: components["schemas"]["PaginationDetail"]
    }
    PaginationDetail: {
      hasCount: boolean
      /** Format: int64 */
      countLimit: number
      /** Format: int32 */
      totalPages?: number
      /** Format: int64 */
      totalElements?: number
      hasNext: boolean
    }
    VeVoteProposalResult: {
      /** Format: int64 */
      blockNumber: number
      /** Format: int64 */
      blockTimestamp: number
      proposalId: string
      /** @enum {string} */
      support: "AGAINST" | "FOR" | "ABSTAIN"
      totalWeight: number
      /** Format: int32 */
      totalVoters: number
    }
    HistoricProposals: {
      id: string
      proposalId: string
      createdDate: string
      proposer?: string
      title?: string
      /** Format: int32 */
      proposalType?: number
      choices?: string[]
      /** Format: int64 */
      createTime?: number
      /** Format: int64 */
      votingStartTime?: number
      /** Format: int64 */
      votingEndTime?: number
      voteTallies?: number[]
      /** Format: int64 */
      totalVotes?: number
      blockId: string
      /** Format: int64 */
      blockNumber: number
      /** Format: int64 */
      blockTimestamp: number
    }
    PaginatedResponseHistoricProposals: {
      data: components["schemas"]["HistoricProposals"][]
      pagination: components["schemas"]["PaginationDetail"]
    }
    IndexedTransferEvent: {
      id: string
      blockId: string
      /** Format: int64 */
      blockNumber: number
      /** Format: int64 */
      blockTimestamp: number
      txId: string
      from: string
      to: string
      value: string
      tokenAddress?: string
      tokenId?: string
      topics: string[]
      /** @enum {string} */
      eventType: "VET" | "FUNGIBLE_TOKEN" | "NFT" | "SEMI_FUNGIBLE_TOKEN"
    }
    PaginatedResponseIndexedTransferEvent: {
      data: components["schemas"]["IndexedTransferEvent"][]
      pagination: components["schemas"]["PaginationDetail"]
    }
    PaginatedResponseString: {
      data: string[]
      pagination: components["schemas"]["PaginationDetail"]
    }
    Clause: {
      to?: string
      value: string
      data: string
    }
    DecodedEvent: {
      address: string
      topics: string[]
      data: string
      name?: string
      params?: {
        [key: string]: Record<string, never>
      }
    }
    DecodedOutputs: {
      contractAddress?: string
      events: components["schemas"]["DecodedEvent"][]
      transfers: components["schemas"]["TxTransfer"][]
    }
    IndexedTransaction: {
      id: string
      blockId: string
      /** Format: int64 */
      blockNumber: number
      /** Format: int64 */
      blockTimestamp: number
      /** Format: int64 */
      type?: number
      /** Format: int64 */
      size: number
      /** Format: int64 */
      chainTag: number
      blockRef: string
      /** Format: int64 */
      expiration: number
      clauses: components["schemas"]["Clause"][]
      /** Format: int64 */
      gasPriceCoef?: number
      /** Format: int64 */
      gas: number
      maxFeePerGas?: string
      maxPriorityFeePerGas?: string
      dependsOn?: string
      nonce: string
      /** Format: int64 */
      gasUsed: number
      gasPayer: string
      paid: string
      reward: string
      reverted: boolean
      origin: string
      outputs: components["schemas"]["DecodedOutputs"][]
    }
    PaginatedResponseIndexedTransaction: {
      data: components["schemas"]["IndexedTransaction"][]
      pagination: components["schemas"]["PaginationDetail"]
    }
    TxTransfer: {
      sender: string
      recipient: string
      amount: string
    }
    TimeSeriesRecordBigInteger: {
      /** Format: int64 */
      timestamp: number
      value: number
    }
    VetStakedByBlock: {
      total: number
      byLevel: {
        [key: string]: number
      }
    }
    NftHoldersByBlock: {
      /** Format: int64 */
      total: number
      byLevel: {
        [key: string]: number
      }
    }
    TimeSeriesRecordLong: {
      /** Format: int64 */
      timestamp: number
      /** Format: int64 */
      value: number
    }
    ExceptionResponse_Public: {
      id: string
      /** Format: int32 */
      status: number
      message?: string
      error: string
      path: string
      timestamp: number
    }
    IndexedNft_Public: {
      id: string
      tokenId: string
      contractAddress: string
      owner: string
      txId: string
      /** Format: int64 */
      blockNumber: number
      blockId: string
      /** Format: int64 */
      blockTimestamp: number
    }
    PaginatedResponseIndexedNft_Public: {
      data: components["schemas"]["IndexedNft_Public"][]
      pagination: components["schemas"]["PaginationDetail_Public"]
    }
    PaginationDetail_Public: {
      hasCount: boolean
      /** Format: int64 */
      countLimit: number
      /** Format: int32 */
      totalPages?: number
      /** Format: int64 */
      totalElements?: number
      hasNext: boolean
    }
    AppVote: {
      appId: string
      voteWeight: string
    }
    Impact: {
      /** Format: int64 */
      carbon?: number
      /** Format: int64 */
      water?: number
      /** Format: int64 */
      energy?: number
      /** Format: int64 */
      waste_mass?: number
      /** Format: int64 */
      waste_items?: number
      /** Format: int64 */
      waste_reduction?: number
      /** Format: int64 */
      biodiversity?: number
      /** Format: int64 */
      people?: number
      /** Format: int64 */
      timber?: number
      /** Format: int64 */
      plastic?: number
      /** Format: int64 */
      education_time?: number
      /** Format: int64 */
      trees_planted?: number
      /** Format: int64 */
      calories_burned?: number
      /** Format: int64 */
      clean_energy_production_wh?: number
      /** Format: int64 */
      sleep_quality_percentage?: number
    }
    IndexedHistoryEvent: {
      id: string
      blockId: string
      /** Format: int64 */
      blockNumber: number
      /** Format: int64 */
      blockTimestamp: number
      txId: string
      origin?: string
      gasPayer?: string
      reverted?: boolean
      contractAddress?: string
      tokenId?: string
      /** @enum {string} */
      eventName:
        | "B3TR_SWAP_VOT3_TO_B3TR"
        | "B3TR_SWAP_B3TR_TO_VOT3"
        | "B3TR_PROPOSAL_SUPPORT"
        | "B3TR_CLAIM_REWARD"
        | "B3TR_UPGRADE_GM"
        | "B3TR_ACTION"
        | "B3TR_PROPOSAL_VOTE"
        | "B3TR_XALLOCATION_VOTE"
        | "TRANSFER_VET"
        | "TRANSFER_FT"
        | "TRANSFER_NFT"
        | "TRANSFER_SF"
        | "SWAP_VET_TO_FT"
        | "SWAP_FT_TO_VET"
        | "SWAP_FT_TO_FT"
        | "UNKNOWN_TX"
        | "NFT_SALE"
        | "STARGATE_DELEGATE"
        | "STARGATE_STAKE"
        | "STARGATE_CLAIM_REWARDS_BASE"
        | "STARGATE_CLAIM_REWARDS_DELEGATE"
        | "STARGATE_UNDELEGATE"
        | "STARGATE_UNSTAKE"
        | "STARGATE_DELEGATE_ONLY"
        | "VEVOTE_VOTE_CAST"
      to?: string
      from?: string
      value?: string
      appId?: string
      proof?: components["schemas"]["SustainabilityProofV2"]
      roundId?: string
      appVotes?: components["schemas"]["AppVote"][]
      /** @enum {string} */
      support?: "AGAINST" | "FOR" | "ABSTAIN"
      votePower?: string
      voteWeight?: string
      reason?: string
      proposalId?: string
      oldLevel?: string
      newLevel?: string
      inputToken?: string
      outputToken?: string
      inputValue?: string
      outputValue?: string
      tokenAddress?: string
      levelId?: string
      owner?: string
      vetGeneratedVthoRewards?: string
      delegationRewards?: string
      migrated?: boolean
      autorenew?: boolean
      tokenIds?: string[]
      validator?: string
    }
    PaginatedResponseIndexedHistoryEvent: {
      data: components["schemas"]["IndexedHistoryEvent"][]
      pagination: components["schemas"]["PaginationDetail"]
    }
    ProofV2: {
      image?: string
      link?: string
      text?: string
      video?: string
    }
    SustainabilityProofV2: {
      /** Format: int32 */
      version: number
      description?: string
      proof?: components["schemas"]["ProofV2"]
      impact?: components["schemas"]["Impact"]
    }
    XAllocResult: {
      /** Format: int32 */
      roundId: number
      appId: string
      /** Format: int64 */
      voters: number
      totalVotes: number
    }
    PaginatedResponseProposalComment: {
      data: components["schemas"]["ProposalComment"][]
      pagination: components["schemas"]["PaginationDetail"]
    }
    ProposalComment: {
      /** Format: int64 */
      blockNumber: number
      /** Format: int64 */
      blockTimestamp: number
      voter: string
      proposalId: string
      /** @enum {string} */
      support: "AGAINST" | "FOR" | "ABSTAIN"
      weight: number
      power: number
      reason: string
    }
    ProposalResult: {
      proposalId: string
      /** @enum {string} */
      support: "AGAINST" | "FOR" | "ABSTAIN"
      /** Format: int64 */
      voters: number
      totalWeight: number
      totalPower: number
    }
    GMLevelOverview: {
      /** @enum {string} */
      level:
        | "ALL"
        | "EARTH"
        | "MOON"
        | "MERCURY"
        | "VENUS"
        | "MARS"
        | "JUPITER"
        | "SATURN"
        | "URANUS"
        | "NEPTUNE"
        | "GALAXY"
      /** Format: int64 */
      totalNFTs: number
    }
    Action: {
      /** Format: int64 */
      blockNumber: number
      /** Format: int64 */
      blockTimestamp: number
      blockId: string
      appId: string
      distributor: string
      amount: number
      receiver: string
      proof?: components["schemas"]["SustainabilityProofV2"]
    }
    PaginatedResponseAction: {
      data: components["schemas"]["Action"][]
      pagination: components["schemas"]["PaginationDetail"]
    }
    UserOverview: {
      wallet: string
      /** Format: int32 */
      roundId?: number
      date?: string
      /** Format: double */
      totalRewardAmount: number
      /** Format: int64 */
      actionsRewarded: number
      totalImpact?: components["schemas"]["Impact"]
      /** Format: int64 */
      rankByReward?: number
      /** Format: int64 */
      rankByActionsRewarded?: number
      uniqueXAppInteractions: string[]
    }
    PaginatedResponseUserDailyActionSummary: {
      data: components["schemas"]["UserDailyActionSummary"][]
      pagination: components["schemas"]["PaginationDetail"]
    }
    UserDailyActionSummary: {
      entity: string
      date: string
      /** Format: int64 */
      actionsRewarded: number
      totalRewardAmount: number
      totalImpact?: components["schemas"]["Impact"]
    }
    PaginatedResponseUserLeaderboardItem: {
      data: components["schemas"]["UserLeaderboardItem"][]
      pagination: components["schemas"]["PaginationDetail"]
    }
    UserLeaderboardItem: {
      wallet: string
      /** Format: int32 */
      roundId?: number
      date?: string
      /** Format: double */
      totalRewardAmount: number
      /** Format: int64 */
      actionsRewarded: number
      totalImpact?: components["schemas"]["Impact"]
    }
    AppLeaderboardItem: {
      appId: string
      /** Format: int32 */
      roundId?: number
      date?: string
      /** Format: double */
      totalRewardAmount: number
      /** Format: int64 */
      actionsRewarded: number
      totalImpact?: components["schemas"]["Impact"]
    }
    PaginatedResponseAppLeaderboardItem: {
      data: components["schemas"]["AppLeaderboardItem"][]
      pagination: components["schemas"]["PaginationDetail"]
    }
    PaginatedResponseUserAppLeaderboardItem: {
      data: components["schemas"]["UserAppLeaderboardItem"][]
      pagination: components["schemas"]["PaginationDetail"]
    }
    UserAppLeaderboardItem: {
      appId: string
      user: string
      /** Format: int32 */
      roundId?: number
      date?: string
      /** Format: double */
      totalRewardAmount: number
      /** Format: int64 */
      actionsRewarded: number
      totalImpact?: components["schemas"]["Impact"]
    }
    GlobalOverview: {
      /** Format: int32 */
      roundId?: number
      date?: string
      /** Format: double */
      totalRewardAmount: number
      /** Format: int64 */
      actionsRewarded: number
      totalImpact?: components["schemas"]["Impact"]
      /** Format: int64 */
      totalUniqueUserInteractions: number
    }
    AppOverview: {
      appId: string
      /** Format: int32 */
      roundId?: number
      date?: string
      /** Format: double */
      totalRewardAmount: number
      /** Format: int64 */
      actionsRewarded: number
      totalImpact?: components["schemas"]["Impact"]
      /** Format: int64 */
      rankByReward?: number
      /** Format: int64 */
      rankByActionsRewarded?: number
      /** Format: int64 */
      totalUniqueUserInteractions: number
    }
    AmnEndorser: {
      nodeMaster: string
      endorser?: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  getResults: {
    parameters: {
      query?: {
        /** @description Proposal ID to filter by. */
        proposalId?: string
        /** @description Filter by support: AGAINST, FOR, or ABSTAIN. */
        support?: "AGAINST" | "FOR" | "ABSTAIN"
        /**
         * @description The results page number
         * @example 0
         */
        page?: Record<string, never>
        /**
         * @description The results page size
         * @example 20
         */
        size?: Record<string, never>
        /** @description The sort direction */
        direction?: "ASC" | "DESC"
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["PaginatedResponseVeVoteProposalResult"]
        }
      }
      /** @description Validation errors occurred, eg: invalid input */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
      /** @description Service not available */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
    }
  }
  getAllProposals: {
    parameters: {
      query?: {
        page?: number
        proposalId?: string
        size?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["PaginatedResponseHistoricProposals"]
        }
      }
      /** @description Validation errors occurred, eg: invalid input */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
      /** @description Service not available */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
    }
  }
  getAllProposals_1: {
    parameters: {
      query?: {
        page?: number
        proposalId?: string
        size?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["PaginatedResponseHistoricProposals"]
        }
      }
      /** @description Validation errors occurred, eg: invalid input */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
      /** @description Service not available */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
    }
  }
  getTransferEvents: {
    parameters: {
      query?: {
        /**
         * @description To or from address of the transfer event
         * @example 0x995711ADca070C8f6cC9ca98A5B9C5A99b8350b1
         */
        address?: string
        /** @description The token contract address */
        tokenAddress?: string
        /**
         * @description The results page number
         * @example 0
         */
        page?: Record<string, never>
        /**
         * @description The results page size
         * @example 20
         */
        size?: Record<string, never>
        /** @description The sort direction */
        direction?: "ASC" | "DESC"
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["PaginatedResponseIndexedTransferEvent"]
        }
      }
      /** @description Validation errors occurred, eg: invalid input */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
      /** @description Service not available */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
    }
  }
  getTransferEventsByTo: {
    parameters: {
      query: {
        /**
         * @description To address of the transfer event
         * @example 0x995711ADca070C8f6cC9ca98A5B9C5A99b8350b1
         */
        address: string
        /** @description The token contract address */
        tokenAddress?: string
        /**
         * @description The results page number
         * @example 0
         */
        page?: Record<string, never>
        /**
         * @description The results page size
         * @example 20
         */
        size?: Record<string, never>
        /** @description The sort direction */
        direction?: "ASC" | "DESC"
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["PaginatedResponseIndexedTransferEvent"]
        }
      }
      /** @description Validation errors occurred, eg: invalid input */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
      /** @description Service not available */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
    }
  }
  getFungibleTokensContractsByAddress: {
    parameters: {
      query: {
        /**
         * @description The address of origin or destination of the fungible tokens transfer events
         * @example 0xf077b491b355E64048cE21E3A6Fc4751eEeA77fa
         */
        address: string
        /**
         * @description If set to true, only official tokens will be returned. Defaults to false.
         * @example false
         */
        officialTokensOnly?: boolean
        /**
         * @description The results page number
         * @example 0
         */
        page?: Record<string, never>
        /**
         * @description The results page size
         * @example 20
         */
        size?: Record<string, never>
        /** @description The sort direction */
        direction?: "ASC" | "DESC"
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["PaginatedResponseString"]
        }
      }
      /** @description Validation errors occurred, eg: invalid input */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
      /** @description Service not available */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
    }
  }
  getTransferEventsByFrom: {
    parameters: {
      query: {
        /**
         * @description From address of the transfer event
         * @example 0x995711ADca070C8f6cC9ca98A5B9C5A99b8350b1
         */
        address: string
        /** @description The token contract address */
        tokenAddress?: string
        /**
         * @description The results page number
         * @example 0
         */
        page?: Record<string, never>
        /**
         * @description The results page size
         * @example 20
         */
        size?: Record<string, never>
        /** @description The sort direction */
        direction?: "ASC" | "DESC"
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["PaginatedResponseIndexedTransferEvent"]
        }
      }
      /** @description Validation errors occurred, eg: invalid input */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
      /** @description Service not available */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
    }
  }
  getTransfersForBlock: {
    parameters: {
      query: {
        /**
         * @description Addresses to query. Max 20 addresses
         * @example [
         *       "0x995711ADca070C8f6cC9ca98A5B9C5A99b8350b1"
         *     ]
         */
        addresses: unknown[]
        /**
         * @description Block number to query
         * @example 1000000
         */
        blockNumber: number
        /**
         * @description The results page number
         * @example 0
         */
        page?: Record<string, never>
        /**
         * @description The results page size
         * @example 20
         */
        size?: Record<string, never>
        /** @description The sort direction */
        direction?: "ASC" | "DESC"
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["PaginatedResponseIndexedTransferEvent"]
        }
      }
      /** @description Validation errors occurred, eg: invalid input */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
      /** @description Service not available */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
    }
  }
  getTransactionsByOriginOrDelegator: {
    parameters: {
      query: {
        /**
         * @description Address of the transaction origin
         * @example 0xf077b491b355E64048cE21E3A6Fc4751eEeA77fa
         */
        origin: string
        /**
         * @description Whether to include transactions the address paid gas for
         * @example false
         */
        includeDelegated?: boolean
        /**
         * @description Whether to return the expanded model
         * @example true
         */
        expanded?: boolean
        /**
         * @description The results page number
         * @example 0
         */
        page?: Record<string, never>
        /**
         * @description The results page size
         * @example 20
         */
        size?: Record<string, never>
        /** @description The sort direction */
        direction?: "ASC" | "DESC"
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["PaginatedResponseIndexedTransaction"]
        }
      }
      /** @description Validation errors occurred, eg: invalid input */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
      /** @description Service not available */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
    }
  }
  getTransactionById: {
    parameters: {
      query?: {
        /**
         * @description Whether to return the expanded model
         * @example true
         */
        expanded?: boolean
      }
      header?: never
      path: {
        /**
         * @description A valid transaction ID
         * @example 0xacc8566c931235a43a775120d48680278d42fa12111aa3c4d4e3a7e8cfcd360a
         */
        txId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["IndexedTransaction"]
        }
      }
      /** @description Validation errors occurred, eg: invalid input */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
      /** @description Service not available */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
    }
  }
  getDelegatedTransactions: {
    parameters: {
      query: {
        /**
         * @description The address of the delegator
         * @example 0x995711ADca070C8f6cC9ca98A5B9C5A99b8350b1
         */
        delegator: string
        /**
         * @description Whether to return the expanded model
         * @example true
         */
        expanded?: boolean
        /**
         * @description The results page number
         * @example 0
         */
        page?: Record<string, never>
        /**
         * @description The results page size
         * @example 20
         */
        size?: Record<string, never>
        /** @description The sort direction */
        direction?: "ASC" | "DESC"
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["PaginatedResponseIndexedTransaction"]
        }
      }
      /** @description Validation errors occurred, eg: invalid input */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
      /** @description Service not available */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
    }
  }
  getTransactionsByContract: {
    parameters: {
      query: {
        /**
         * @description The contract address to query transactions for
         * @example 0x0000000000000000000000000000456e65726779
         */
        contractAddress: string
        /**
         * @description Whether to return the expanded model
         * @example true
         */
        expanded?: boolean
        /**
         * @description The results page number
         * @example 0
         */
        page?: Record<string, never>
        /**
         * @description The results page size
         * @example 20
         */
        size?: Record<string, never>
        /** @description The sort direction */
        direction?: "ASC" | "DESC"
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["PaginatedResponseIndexedTransaction"]
        }
      }
      /** @description Validation errors occurred, eg: invalid input */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
      /** @description Service not available */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
    }
  }
  getTotalVthoClaimed: {
    parameters: {
      query?: {
        /**
         * @description Optional query parameter to get the total VTHO claimed at a specific block number. If not provided, the latest value will be returned.
         * @example 12345678
         */
        blockNumber?: Record<string, never>
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": number
        }
      }
      /** @description Validation errors occurred, eg: invalid input */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
      /** @description Service not available */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
    }
  }
  getTotalVthoClaimed_1: {
    parameters: {
      query?: never
      header?: never
      path: {
        /**
         * @description The account address to query for total VTHO claimed
         * @example 0xf077b491b355E64048cE21E3A6Fc4751eEeA77fa
         */
        account: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": number
        }
      }
      /** @description Validation errors occurred, eg: invalid input */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
      /** @description Service not available */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
    }
  }
  getTotalVthoClaimed_2: {
    parameters: {
      query?: never
      header?: never
      path: {
        /**
         * @description Time range preset to use for the query.
         * @example 1-day
         */
        range: "1-hour" | "1-day" | "1-week" | "1-month" | "1-year" | "all"
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["TimeSeriesRecordBigInteger"][]
        }
      }
      /** @description Validation errors occurred, eg: invalid input */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
      /** @description Service not available */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
    }
  }
  getTotalVetStaked: {
    parameters: {
      query?: {
        /**
         * @description Optional query parameter to get the total VET staked at a specific block number. If not provided, the latest value will be returned.
         * @example 12345678
         */
        blockNumber?: Record<string, never>
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["VetStakedByBlock"]
        }
      }
      /** @description Validation errors occurred, eg: invalid input */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
      /** @description Service not available */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
    }
  }
  getTotalVetStaked_1: {
    parameters: {
      query?: {
        /** @description Optional query parameter to filter total VET staked by level. If not provided, all levels will be included. */
        level?:
          | "Strength"
          | "Thunder"
          | "Mjolnir"
          | "VeThorX"
          | "StrengthX"
          | "ThunderX"
          | "MjolnirX"
          | "Dawn"
          | "Lightning"
          | "Flash"
      }
      header?: never
      path: {
        /**
         * @description Time range preset to use for the query.
         * @example 1-day
         */
        range: "1-hour" | "1-day" | "1-week" | "1-month" | "1-year" | "all"
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["TimeSeriesRecordBigInteger"][]
        }
      }
      /** @description Validation errors occurred, eg: invalid input */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
      /** @description Service not available */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
    }
  }
  getNftHolders: {
    parameters: {
      query?: {
        /**
         * @description Optional query parameter to get the total number of NFT holders at a specific block number. If not provided, the latest value will be returned.
         * @example 12345678
         */
        blockNumber?: Record<string, never>
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["NftHoldersByBlock"]
        }
      }
      /** @description Validation errors occurred, eg: invalid input */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
      /** @description Service not available */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
    }
  }
  getNftHolders_1: {
    parameters: {
      query?: {
        /** @description Optional query parameter to filter NFT holders by level. If not provided, all levels will be included. */
        level?:
          | "Strength"
          | "Thunder"
          | "Mjolnir"
          | "VeThorX"
          | "StrengthX"
          | "ThunderX"
          | "MjolnirX"
          | "Dawn"
          | "Lightning"
          | "Flash"
      }
      header?: never
      path: {
        /**
         * @description Time range preset to use for the query.
         * @example 1-day
         */
        range: "1-hour" | "1-day" | "1-week" | "1-month" | "1-year" | "all"
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["TimeSeriesRecordLong"][]
        }
      }
      /** @description Validation errors occurred, eg: invalid input */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
      /** @description Service not available */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
    }
  }
  getOwnedNFTs: {
    parameters: {
      query: {
        /**
         * @description Address of the NFT owner
         * @example 0xf077b491b355E64048cE21E3A6Fc4751eEeA77fa
         */
        address: string
        /** @description The contract address */
        contractAddress?: string
        /** @description The NFT tokenId */
        tokenId?: string
        /**
         * @description The results page number
         * @example 0
         */
        page?: Record<string, never>
        /**
         * @description The results page size
         * @example 20
         */
        size?: Record<string, never>
        /** @description The sort direction */
        direction?: "ASC" | "DESC"
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["PaginatedResponseIndexedNft_Public"]
        }
      }
      /** @description Validation errors occurred, eg: invalid input */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse_Public"]
        }
      }
      /** @description Service not available */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse_Public"]
        }
      }
    }
  }
  getContractsByNFTOwner: {
    parameters: {
      query: {
        /**
         * @description The address of the NFTs owner
         * @example 0xf077b491b355E64048cE21E3A6Fc4751eEeA77fa
         */
        owner: string
        /**
         * @description The results page number
         * @example 0
         */
        page?: Record<string, never>
        /**
         * @description The results page size
         * @example 20
         */
        size?: Record<string, never>
        /** @description The sort direction */
        direction?: "ASC" | "DESC"
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Invalid address supplied */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["PaginatedResponseString"]
        }
      }
    }
  }
  getUsersHistory: {
    parameters: {
      query?: {
        /** @description Filter by specific transaction names. */
        eventName?: (
          | "B3TR_SWAP_VOT3_TO_B3TR"
          | "B3TR_SWAP_B3TR_TO_VOT3"
          | "B3TR_PROPOSAL_SUPPORT"
          | "B3TR_CLAIM_REWARD"
          | "B3TR_UPGRADE_GM"
          | "B3TR_ACTION"
          | "B3TR_PROPOSAL_VOTE"
          | "B3TR_XALLOCATION_VOTE"
          | "TRANSFER_VET"
          | "TRANSFER_FT"
          | "TRANSFER_NFT"
          | "TRANSFER_SF"
          | "SWAP_VET_TO_FT"
          | "SWAP_FT_TO_VET"
          | "SWAP_FT_TO_FT"
          | "UNKNOWN_TX"
          | "NFT_SALE"
          | "STARGATE_DELEGATE"
          | "STARGATE_STAKE"
          | "STARGATE_CLAIM_REWARDS_BASE"
          | "STARGATE_CLAIM_REWARDS_DELEGATE"
          | "STARGATE_UNDELEGATE"
          | "STARGATE_UNSTAKE"
          | "STARGATE_DELEGATE_ONLY"
          | "VEVOTE_VOTE_CAST"
        )[]
        /** @description Array of fields to search by. */
        searchBy?: ("to" | "from" | "origin" | "gasPayer")[]
        /** @description The contract address */
        contractAddress?: string
        /** @description Return transactions after and including this timestamp (Unix time in seconds). */
        after?: Record<string, never>
        /** @description Return transactions before and including this timestamp (Unix time in seconds). */
        before?: Record<string, never>
        /**
         * @description The results page number
         * @example 0
         */
        page?: Record<string, never>
        /**
         * @description The results page size
         * @example 20
         */
        size?: Record<string, never>
        /** @description The sort direction */
        direction?: "ASC" | "DESC"
      }
      header?: never
      path: {
        /**
         * @description A valid account address
         * @example 0xf077b491b355e64048ce21e3a6fc4751eeea77fa
         */
        account: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["PaginatedResponseIndexedHistoryEvent"]
        }
      }
      /** @description Validation errors occurred, eg: invalid input */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
      /** @description Service not available */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
    }
  }
  getAllocationVoteResults: {
    parameters: {
      query?: never
      header?: never
      path: {
        /**
         * @description Round to filter by.
         * @example 2
         */
        roundId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["XAllocResult"][]
        }
      }
      /** @description Validation errors occurred, eg: invalid input */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
      /** @description Service not available */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
    }
  }
  getUserProposalComments: {
    parameters: {
      query?: {
        /** @description Proposal ID to filter by. */
        proposalId?: string
        /** @description Filter by support. */
        support?: "FOR" | "AGAINST" | "ABSTAIN"
        /**
         * @description The results page number
         * @example 0
         */
        page?: Record<string, never>
        /**
         * @description The results page size
         * @example 20
         */
        size?: Record<string, never>
        /** @description The sort direction */
        direction?: "ASC" | "DESC"
      }
      header?: never
      path: {
        /** @description Wallet address. */
        wallet: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["PaginatedResponseProposalComment"]
        }
      }
      /** @description Validation errors occurred, eg: invalid input */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
      /** @description Service not available */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
    }
  }
  getProposalResult: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Proposal ID to filter by. */
        proposalId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["ProposalResult"][]
        }
      }
      /** @description Validation errors occurred, eg: invalid input */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
      /** @description Service not available */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
    }
  }
  getProposalComments: {
    parameters: {
      query?: {
        /** @description Filter by support. */
        support?: "FOR" | "AGAINST" | "ABSTAIN"
        /**
         * @description The results page number
         * @example 0
         */
        page?: Record<string, never>
        /**
         * @description The results page size
         * @example 20
         */
        size?: Record<string, never>
        /** @description The sort direction */
        direction?: "ASC" | "DESC"
      }
      header?: never
      path: {
        /** @description Proposal ID to filter by. */
        proposalId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["PaginatedResponseProposalComment"]
        }
      }
      /** @description Validation errors occurred, eg: invalid input */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
      /** @description Service not available */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
    }
  }
  getLevelOverviews: {
    parameters: {
      query?: {
        /** @description Optional level to filter by */
        level?:
          | "ALL"
          | "EARTH"
          | "MOON"
          | "MERCURY"
          | "VENUS"
          | "MARS"
          | "JUPITER"
          | "SATURN"
          | "URANUS"
          | "NEPTUNE"
          | "GALAXY"
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["GMLevelOverview"][]
        }
      }
      /** @description Validation errors occurred, eg: invalid input */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
      /** @description Service not available */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
    }
  }
  getUserActions: {
    parameters: {
      query?: {
        /** @description App ID to query by. */
        appId?: string
        /** @description Return transactions after this timestamp (Unix time in milliseconds). */
        after?: Record<string, never>
        /** @description Return transactions before this timestamp (Unix time in milliseconds). */
        before?: Record<string, never>
        /**
         * @description The results page number
         * @example 0
         */
        page?: Record<string, never>
        /**
         * @description The results page size
         * @example 20
         */
        size?: Record<string, never>
        /** @description The sort direction */
        direction?: "ASC" | "DESC"
      }
      header?: never
      path: {
        /** @description Wallet address. */
        wallet: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["PaginatedResponseAction"]
        }
      }
    }
  }
  getUserOverview: {
    parameters: {
      query?: {
        roundId?: number
        date?: string
      }
      header?: never
      path: {
        /** @description Wallet address. */
        wallet: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["UserOverview"]
        }
      }
      /** @description Validation errors occurred, eg: invalid input */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
      /** @description Service not available */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
    }
  }
  getDailySummariesForRange: {
    parameters: {
      query: {
        /** @description A date to filter by. In UTC, format: yyyy-MM-dd. */
        startDate: string
        /** @description A date to filter by. In UTC, format: yyyy-MM-dd. */
        endDate: string
        /**
         * @description The results page number
         * @example 0
         */
        page?: Record<string, never>
        /**
         * @description The results page size
         * @example 20
         */
        size?: Record<string, never>
        /** @description The sort direction */
        direction?: "ASC" | "DESC"
      }
      header?: never
      path: {
        /** @description Wallet address. */
        wallet: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["PaginatedResponseUserDailyActionSummary"]
        }
      }
      /** @description Validation errors occurred, eg: invalid input */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
      /** @description Service not available */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
    }
  }
  getUserLeaderboard: {
    parameters: {
      query?: {
        /** @description Round ID to filter by. */
        roundId?: number
        date?: string
        /**
         * @description The results page number
         * @example 0
         */
        page?: Record<string, never>
        /**
         * @description The results page size
         * @example 20
         */
        size?: Record<string, never>
        /** @description The sort direction */
        direction?: "ASC" | "DESC"
        /** @description The sort by field */
        sortBy?: "totalRewardAmount" | "actionsRewarded"
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["PaginatedResponseUserLeaderboardItem"]
        }
      }
      /** @description Validation errors occurred, eg: invalid input */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
      /** @description Service not available */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
    }
  }
  getAppLeaderboard: {
    parameters: {
      query?: {
        /** @description Round ID to filter by. */
        roundId?: number
        /** @description A date to filter by. In UTC, format: yyyy-MM-dd. */
        date?: string
        /**
         * @description The results page number
         * @example 0
         */
        page?: Record<string, never>
        /**
         * @description The results page size
         * @example 20
         */
        size?: Record<string, never>
        /** @description The sort direction */
        direction?: "ASC" | "DESC"
        /** @description The sort by field */
        sortBy?: "totalRewardAmount" | "actionsRewarded"
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["PaginatedResponseAppLeaderboardItem"]
        }
      }
      /** @description Validation errors occurred, eg: invalid input */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
      /** @description Service not available */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
    }
  }
  getUserAppLeaderboard: {
    parameters: {
      query?: {
        /** @description Round ID to filter by. */
        roundId?: number
        /** @description A date to filter by. In UTC, format: yyyy-MM-dd. */
        date?: string
        /**
         * @description The results page number
         * @example 0
         */
        page?: Record<string, never>
        /**
         * @description The results page size
         * @example 20
         */
        size?: Record<string, never>
        /** @description The sort direction */
        direction?: "ASC" | "DESC"
        /** @description The sort by field */
        sortBy?: "totalRewardAmount" | "actionsRewarded"
      }
      header?: never
      path: {
        /** @description App ID to query by. */
        appId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["PaginatedResponseUserAppLeaderboardItem"]
        }
      }
      /** @description Validation errors occurred, eg: invalid input */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
      /** @description Service not available */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
    }
  }
  getGlobalOverview: {
    parameters: {
      query?: {
        /** @description Round ID to filter by. */
        roundId?: number
        /** @description A date to filter by. In UTC, format: yyyy-MM-dd. */
        date?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["GlobalOverview"]
        }
      }
      /** @description Validation errors occurred, eg: invalid input */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
      /** @description Service not available */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
    }
  }
  getAppActions: {
    parameters: {
      query?: {
        /** @description Return transactions after this timestamp (Unix time in milliseconds). */
        after?: Record<string, never>
        /** @description Return transactions before this timestamp (Unix time in milliseconds). */
        before?: Record<string, never>
        /**
         * @description The results page number
         * @example 0
         */
        page?: Record<string, never>
        /**
         * @description The results page size
         * @example 20
         */
        size?: Record<string, never>
        /** @description The sort direction */
        direction?: "ASC" | "DESC"
      }
      header?: never
      path: {
        /** @description App ID to query by. */
        appId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["PaginatedResponseAction"]
        }
      }
    }
  }
  getAppOverview: {
    parameters: {
      query?: {
        roundId?: number
        /** @description A date to filter by. In UTC, format: yyyy-MM-dd. */
        date?: string
      }
      header?: never
      path: {
        /** @description App ID to query by. */
        appId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["AppOverview"]
        }
      }
      /** @description Validation errors occurred, eg: invalid input */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
      /** @description Service not available */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
    }
  }
  checkUserIsEndorser: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description User address to check if they are an endorser. */
        user: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["AmnEndorser"]
        }
      }
      /** @description Validation errors occurred, eg: invalid input */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
      /** @description Service not available */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
    }
  }
  checkUserIsEndorser_1: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description User address to check if they are an endorser. */
        user: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["AmnEndorser"]
        }
      }
      /** @description Validation errors occurred, eg: invalid input */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
      /** @description Service not available */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ExceptionResponse"]
        }
      }
    }
  }
}
