project_name: b3tr-frontend
project_slug: governance-frontend
environment: dev
region: eu-west-1
account_id: "211125319139"

hosted_zone_name: testnet.governance.vebetterdao.org

# Optional role to assume when running Terraform (leave blank to use caller credentials)
# assume_role_arn: "arn:aws:iam::211125319139:role/terraform-deployer"

ecr_repository_name: governance-frontend
