---
# AWS Configuration
aws_region: eu-west-1
aws_account_id: "851725442887"
environment: "mainnet"

# Lambda Configuration
lambda_function_name: "resetUserSignalsWithReason_vebetterpassport_mainnet"
lambda_handler: "index.handler"
lambda_runtime: "nodejs20.x"
lambda_memory_size: 128
lambda_timeout: 30

# Lambda Build Path
lambda_source_dir: "packages/lambda/dist/mainnet/resetSignalCounter" 