# B3TR Storybook - Production Environment Configuration
project: b3tr
environment: prod
region: eu-west-1
account_id: "211125319139"

# Domain configuration
domain: storybook.b3tr.vechain.org
base_domain: b3tr.vechain.org

