
module "datadog_integration_aws" {
  source              = "git::git@github.com:vechain/terraform_infrastructure_modules.git//datadog?ref=v.1.0.50"
  enable_datadog_integration_aws = terraform.workspace == "dev" ? true : false
  project_name        = "b3tr-dev"
  role_name           = "DatadogAWSIntegrationRole"
  aws_permissions_list = [
                "apigateway:GET",
                "autoscaling:Describe*",
                "cloudfront:GetDistributionConfig",
                "cloudfront:ListDistributions",
                "cloudtrail:DescribeTrails",
                "cloudtrail:GetTrailStatus",
                "cloudtrail:LookupEvents",
                "cloudwatch:Describe*",
                "cloudwatch:Get*",
                "cloudwatch:List*",
                "elasticloadbalancing:Describe*",
                "events:CreateEventBus",
                "health:DescribeEvents",
                "health:DescribeEventDetails",
                "health:DescribeAffectedEntities",
                "lambda:GetPolicy",
                "lambda:List*",
                "logs:DeleteSubscriptionFilter",
                "logs:DescribeLogGroups",
                "logs:DescribeLogStreams",
                "logs:DescribeSubscriptionFilters",
                "logs:FilterLogEvents",
                "logs:PutSubscriptionFilter",
                "logs:TestMetricFilter",
                "route53:List*",
                "s3:GetBucketLogging",
                "s3:GetBucketLocation",
                "s3:GetBucketNotification",
                "s3:GetBucketTagging",
                "s3:ListAllMyBuckets",
                "s3:PutBucketNotification",
                "sqs:ListQueues",
                "states:ListStateMachines",
                "states:DescribeStateMachine",
                "tag:GetResources",
                "tag:GetTagKeys",
                "tag:GetTagValues",
  ]

  filter_tags          = []
  host_tags            = ["Env:b3tr-dev"]
  excluded_regions     = ["us-east-2, us-west-1, us-west-2, ca-central-1, eu-west-2, eu-west-3, eu-central-1, eu-north-1, ap-south-1, ap-northeast-1, ap-northeast-2, ap-southeast-1, ap-southeast-2, sa-east-1"]
  secret_id             = local.config.secret_id
  
  create_api_gateway_group = false
  create_ecs_group         = false
  create_elb_group         = false
  create_s3_group          = false
  create_lambda_group      = false
  create_cloudfront_group  = false
  create_monitor           = false
  create_dynamic_dashboard = false


monitors = {
}
synthetics_monitors = {}

}

resource "datadog_dashboard" "tfer--dashboard_iik-ufg-sza" {
  description  = "b3tr-prod Dashboard generated by Terraform Module"
  layout_type  = "ordered"
  reflow_type  = "fixed"
  title        = "b3tr-prod Dashboard"
  url          = "/dashboard/iik-ufg-sza/b3tr-prod-dashboard"

  widget {
    geomap_definition {
      request {
        formula {
          formula_expression = "query1"
        }

        query {
          event_query {
            compute {
              aggregation = "count"
              interval    = "0"
              metric      = "count"
            }

            data_source = "rum"

            group_by {
              facet = "@geo.country_iso_code"
              limit = "250"

              sort {
                aggregation = "count"
                metric      = "count"
                order       = "desc"
              }
            }

            indexes = ["*"]
            name    = "query1"

            search {
              query = "@type:session @application.id:3b19a7c7-f03e-4c05-a83b-3b65d2ed489a @session.type:user"
            }

            storage = "hot"
          }
        }
      }

      style {
        palette      = "Viridis"
        palette_flip = "false"
      }

      title       = "Number of Sessions by Country"
      title_align = "left"
      title_size  = "16"

      view {
        focus = "WORLD"
      }
    }

    widget_layout {
      height          = "4"
      is_column_break = "false"
      width           = "6"
      x               = "0"
      y               = "0"
    }
  }

  widget {
    list_stream_definition {
      request {
        columns {
          field = "count"
          width = "auto"
        }

        columns {
          field = "details"
          width = "auto"
        }

        columns {
          field = "volume"
          width = "auto"
        }

        query {
          data_source  = "rum_issue_stream"
          query_string = "@session.type:user @application.id:3b19a7c7-f03e-4c05-a83b-3b65d2ed489a"
        }

        response_format = "event_list"
      }

      title       = "Ongoing Issues"
      title_align = "left"
      title_size  = "16"
    }

    widget_layout {
      height          = "4"
      is_column_break = "false"
      width           = "6"
      x               = "6"
      y               = "8"
    }
  }

  widget {
    query_table_definition {
      has_search_bar = "never"

      request {
        formula {
          alias              = "Affected Sessions"
          cell_display_mode  = "bar"
          formula_expression = "query1"

          limit {
            count = "10"
            order = "desc"
          }
        }

        formula {
          alias             = "Total Errors"
          cell_display_mode = "bar"

          conditional_formats {
            comparator = ">"
            hide_value = "false"
            palette    = "red_on_white"
            value      = "0"
          }

          formula_expression = "query2"
        }

        limit = "0"

        query {
          event_query {
            compute {
              aggregation = "cardinality"
              interval    = "0"
              metric      = "@session.id"
            }

            data_source = "rum"

            group_by {
              facet = "@action.name"
              limit = "10"

              sort {
                aggregation = "cardinality"
                metric      = "@session.id"
                order       = "desc"
              }
            }

            group_by {
              facet = "@view.name"
              limit = "10"

              sort {
                aggregation = "cardinality"
                metric      = "@session.id"
                order       = "desc"
              }
            }

            indexes = ["*"]
            name    = "query1"

            search {
              query = "@type:action @action.error.count:>0 @session.type:user @application.id:3b19a7c7-f03e-4c05-a83b-3b65d2ed489a"
            }
          }
        }

        query {
          event_query {
            compute {
              aggregation = "count"
              interval    = "0"
            }

            data_source = "rum"

            group_by {
              facet = "@action.name"
              limit = "10"

              sort {
                aggregation = "cardinality"
                metric      = "@session.id"
                order       = "desc"
              }
            }

            group_by {
              facet = "@view.name"
              limit = "10"

              sort {
                aggregation = "cardinality"
                metric      = "@session.id"
                order       = "desc"
              }
            }

            indexes = ["*"]
            name    = "query2"

            search {
              query = "@type:action @action.error.count:>0 @session.type:user @application.id:3b19a7c7-f03e-4c05-a83b-3b65d2ed489a"
            }
          }
        }
      }

      title       = "Top Actions Triggering Errors"
      title_align = "left"
      title_size  = "16"
    }

    widget_layout {
      height          = "4"
      is_column_break = "false"
      width           = "6"
      x               = "0"
      y               = "8"
    }
  }

  widget {
    sunburst_definition {
      hide_total = "false"

      legend_table {
        type = "table"
      }

      request {
        formula {
          formula_expression = "query1"
        }

        query {
          event_query {
            compute {
              aggregation = "count"
              interval    = "0"
              metric      = "count"
            }

            data_source = "rum"

            group_by {
              facet = "@geo.country"
              limit = "10"

              sort {
                aggregation = "count"
                metric      = "count"
                order       = "desc"
              }
            }

            group_by {
              facet = "@geo.country_subdivision"
              limit = "10"

              sort {
                aggregation = "count"
                metric      = "count"
                order       = "desc"
              }
            }

            indexes = ["*"]
            name    = "query1"

            search {
              query = "@type:session @application.id:3b19a7c7-f03e-4c05-a83b-3b65d2ed489a @session.type:user"
            }

            storage = "hot"
          }
        }

        style {
          palette = "datadog16"
        }
      }

      title       = "Region Breakdown"
      title_align = "left"
      title_size  = "16"
    }

    widget_layout {
      height          = "4"
      is_column_break = "false"
      width           = "6"
      x               = "6"
      y               = "0"
    }
  }

  widget {
    sunburst_definition {
      hide_total = "false"

      request {
        formula {
          formula_expression = "query1"
        }

        query {
          event_query {
            compute {
              aggregation = "count"
              interval    = "0"
              metric      = "count"
            }

            data_source = "rum"

            group_by {
              facet = "@device.type"
              limit = "10"

              sort {
                aggregation = "count"
                metric      = "count"
                order       = "desc"
              }
            }

            indexes = ["*"]
            name    = "query1"

            search {
              query = "@type:session @application.id:3b19a7c7-f03e-4c05-a83b-3b65d2ed489a @session.type:user"
            }

            storage = "hot"
          }
        }

        style {
          palette = "dog_classic"
        }
      }

      title       = "Device Type"
      title_align = "left"
      title_size  = "16"
    }

    widget_layout {
      height          = "4"
      is_column_break = "false"
      width           = "6"
      x               = "6"
      y               = "4"
    }
  }

  widget {
    timeseries_definition {
      legend_columns = ["avg", "max", "min", "sum", "value"]
      legend_layout  = "auto"

      request {
        display_type = "bars"

        formula {
          formula_expression = "a"
        }

        on_right_yaxis = "false"

        query {
          event_query {
            compute {
              aggregation = "count"
              interval    = "86400000"
              metric      = "count"
            }

            data_source = "rum"
            indexes     = ["*"]
            name        = "a"

            search {
              query = "@type:session @application.id:3b19a7c7-f03e-4c05-a83b-3b65d2ed489a @session.type:user"
            }

            storage = "hot"
          }
        }

        style {
          palette = "dog_classic"
        }
      }

      show_legend = "false"
      title       = "Number of Sessions by Day"
      title_align = "left"
      title_size  = "16"
    }

    widget_layout {
      height          = "4"
      is_column_break = "false"
      width           = "6"
      x               = "0"
      y               = "4"
    }
  }
}
