module "datadog_integration_aws" {
  source       = "git::git@github.com:vechain/terraform_infrastructure_modules.git//datadog?ref=v.1.4.6"
  project_name = "${local.env.project}-${local.env.app_name}"
  role_name    = "DatadogAWSIntegrationRole"
  aws_permissions_list = [
    "autoscaling:Describe*",
    "budgets:ViewBudget",
    "cloudfront:GetDistributionConfig",
    "cloudfront:ListDistributions",
    "cloudtrail:DescribeTrails",
    "cloudtrail:GetTrailStatus",
    "cloudtrail:LookupEvents",
    "cloudwatch:Describe*",
    "cloudwatch:Get*",
    "cloudwatch:List*",
    "dynamodb:List*",
    "dynamodb:Describe*",
    "ec2:Describe*",
    "ec2:GetTransitGatewayPrefixListReferences",
    "ec2:SearchTransitGatewayRoutes",
    "ecs:List*",
    "ecs:Describe*",
    "elasticache:Describe*",
    "elasticache:List*",
    "es:ListTags",
    "es:ListDomainNames",
    "es:DescribeElasticsearchDomains",
    "events:CreateEventBus",
    "health:DescribeEvents",
    "health:DescribeEventDetails",
    "health:DescribeAffectedEntities",
    "lambda:GetPolicy",
    "lambda:List*",
    "logs:DeleteSubscriptionFilter",
    "logs:DescribeLogGroups",
    "logs:DescribeLogStreams",
    "logs:DescribeSubscriptionFilters",
    "logs:FilterLogEvents",
    "logs:PutSubscriptionFilter",
    "logs:TestMetricFilter",
    "rds:Describe*",
    "rds:List*",
    "route53:List*",
    "s3:Get*",
    "s3:List*",
    "s3:PutBucketNotification",
    "ses:Get*",
    "sns:List*",
    "sns:Publish",
    "sqs:ListQueues",
    "tag:GetResources",
    "tag:GetTagKeys",
    "tag:GetTagValues",
    "elasticloadbalancing:DescribeLoadBalancers",
    "elasticloadbalancing:DescribeTargetGroups",
    "elasticloadbalancing:DescribeTrustStores",
    "states:ListStateMachines"
  ]

  filter_tags      = []
  host_tags        = ["Env:b3tr-indexer"]
  excluded_regions = [
  "us-east-2", "us-west-1", "us-west-2", "ca-central-1", "eu-west-2", "eu-west-3", "eu-central-1", "eu-north-1",
  "ap-south-1", "ap-northeast-1", "ap-northeast-2", "ap-southeast-1", "ap-southeast-2", "sa-east-1", "af-south-1",
  "ap-east-1", "ap-northeast-3", "ap-south-2", "ap-southeast-3", "ap-southeast-4", "ca-west-1", "eu-central-2",
  "eu-south-1", "eu-south-2", "il-central-1", "me-central-1", "me-south-1"
]


  secret_id        = "arn:aws:secretsmanager:eu-west-1:851725442887:secret:datadog_keys-thEjHX"
  lambda_secret_id = "arn:aws:secretsmanager:eu-west-1:851725442887:secret:datadog_log_forwarder_api_key-BnUkCG"

  enable_datadog_integration_aws = true
  create_ecs_group        = true
  create_elb_group        = true
  create_s3_group         = true
  create_cloudfront_group = true
  create_monitor          = false
  enable_logging          = true
  logging_services        = ["elbv2", "cloudfront", "lambda"]
  namespace_rules         = {"ecs":true}
  create_synthetics_monitor = false
  create_dynamodb_group    = true


  monitors = {
  }

  synthetics_monitors = {
  }
}

resource "datadog_dashboard" "tfer--dashboard_iik-ufg-sza" {
  description  = "b3tr-prod Dashboard generated by Terraform Module"
  layout_type  = "ordered"
  reflow_type  = "fixed"
  title        = "b3tr-prod Dashboard"
  url          = "/dashboard/iik-ufg-sza/b3tr-prod-dashboard"

  widget {
    geomap_definition {
      request {
        formula {
          formula_expression = "query1"
        }

        query {
          event_query {
            compute {
              aggregation = "count"
              interval    = "0"
              metric      = "count"
            }

            data_source = "rum"

            group_by {
              facet = "@geo.country_iso_code"
              limit = "250"

              sort {
                aggregation = "count"
                metric      = "count"
                order       = "desc"
              }
            }

            indexes = ["*"]
            name    = "query1"

            search {
              query = "@type:session @application.id:3b19a7c7-f03e-4c05-a83b-3b65d2ed489a @session.type:user"
            }

            storage = "hot"
          }
        }
      }

      style {
        palette      = "Viridis"
        palette_flip = "false"
      }

      title       = "Number of Sessions by Country"
      title_align = "left"
      title_size  = "16"

      view {
        focus = "WORLD"
      }
    }

    widget_layout {
      height          = "4"
      is_column_break = "false"
      width           = "6"
      x               = "0"
      y               = "0"
    }
  }

  widget {
    list_stream_definition {
      request {
        columns {
          field = "count"
          width = "auto"
        }

        columns {
          field = "details"
          width = "auto"
        }

        columns {
          field = "volume"
          width = "auto"
        }

        query {
          data_source  = "rum_issue_stream"
          query_string = "@session.type:user @application.id:3b19a7c7-f03e-4c05-a83b-3b65d2ed489a"
        }

        response_format = "event_list"
      }

      title       = "Ongoing Issues"
      title_align = "left"
      title_size  = "16"
    }

    widget_layout {
      height          = "4"
      is_column_break = "false"
      width           = "6"
      x               = "6"
      y               = "8"
    }
  }

  widget {
    query_table_definition {
      has_search_bar = "never"

      request {
        formula {
          alias              = "Affected Sessions"
          cell_display_mode  = "bar"
          formula_expression = "query1"

          limit {
            count = "10"
            order = "desc"
          }
        }

        formula {
          alias             = "Total Errors"
          cell_display_mode = "bar"

          conditional_formats {
            comparator = ">"
            hide_value = "false"
            palette    = "red_on_white"
            value      = "0"
          }

          formula_expression = "query2"
        }

        limit = "0"

        query {
          event_query {
            compute {
              aggregation = "cardinality"
              interval    = "0"
              metric      = "@session.id"
            }

            data_source = "rum"

            group_by {
              facet = "@action.name"
              limit = "10"

              sort {
                aggregation = "cardinality"
                metric      = "@session.id"
                order       = "desc"
              }
            }

            group_by {
              facet = "@view.name"
              limit = "10"

              sort {
                aggregation = "cardinality"
                metric      = "@session.id"
                order       = "desc"
              }
            }

            indexes = ["*"]
            name    = "query1"

            search {
              query = "@type:action @action.error.count:>0 @session.type:user @application.id:3b19a7c7-f03e-4c05-a83b-3b65d2ed489a"
            }
          }
        }

        query {
          event_query {
            compute {
              aggregation = "count"
              interval    = "0"
            }

            data_source = "rum"

            group_by {
              facet = "@action.name"
              limit = "10"

              sort {
                aggregation = "cardinality"
                metric      = "@session.id"
                order       = "desc"
              }
            }

            group_by {
              facet = "@view.name"
              limit = "10"

              sort {
                aggregation = "cardinality"
                metric      = "@session.id"
                order       = "desc"
              }
            }

            indexes = ["*"]
            name    = "query2"

            search {
              query = "@type:action @action.error.count:>0 @session.type:user @application.id:3b19a7c7-f03e-4c05-a83b-3b65d2ed489a"
            }
          }
        }
      }

      title       = "Top Actions Triggering Errors"
      title_align = "left"
      title_size  = "16"
    }

    widget_layout {
      height          = "4"
      is_column_break = "false"
      width           = "6"
      x               = "0"
      y               = "8"
    }
  }

  widget {
    sunburst_definition {
      hide_total = "false"

      legend_table {
        type = "table"
      }

      request {
        formula {
          formula_expression = "query1"
        }

        query {
          event_query {
            compute {
              aggregation = "count"
              interval    = "0"
              metric      = "count"
            }

            data_source = "rum"

            group_by {
              facet = "@geo.country"
              limit = "10"

              sort {
                aggregation = "count"
                metric      = "count"
                order       = "desc"
              }
            }

            group_by {
              facet = "@geo.country_subdivision"
              limit = "10"

              sort {
                aggregation = "count"
                metric      = "count"
                order       = "desc"
              }
            }

            indexes = ["*"]
            name    = "query1"

            search {
              query = "@type:session @application.id:3b19a7c7-f03e-4c05-a83b-3b65d2ed489a @session.type:user"
            }

            storage = "hot"
          }
        }

        style {
          palette = "datadog16"
        }
      }

      title       = "Region Breakdown"
      title_align = "left"
      title_size  = "16"
    }

    widget_layout {
      height          = "4"
      is_column_break = "false"
      width           = "6"
      x               = "6"
      y               = "0"
    }
  }

  widget {
    sunburst_definition {
      hide_total = "false"

      request {
        formula {
          formula_expression = "query1"
        }

        query {
          event_query {
            compute {
              aggregation = "count"
              interval    = "0"
              metric      = "count"
            }

            data_source = "rum"

            group_by {
              facet = "@device.type"
              limit = "10"

              sort {
                aggregation = "count"
                metric      = "count"
                order       = "desc"
              }
            }

            indexes = ["*"]
            name    = "query1"

            search {
              query = "@type:session @application.id:3b19a7c7-f03e-4c05-a83b-3b65d2ed489a @session.type:user"
            }

            storage = "hot"
          }
        }

        style {
          palette = "dog_classic"
        }
      }

      title       = "Device Type"
      title_align = "left"
      title_size  = "16"
    }

    widget_layout {
      height          = "4"
      is_column_break = "false"
      width           = "6"
      x               = "6"
      y               = "4"
    }
  }

  widget {
    timeseries_definition {
      legend_columns = ["avg", "max", "min", "sum", "value"]
      legend_layout  = "auto"

      request {
        display_type = "bars"

        formula {
          formula_expression = "a"
        }

        on_right_yaxis = "false"

        query {
          event_query {
            compute {
              aggregation = "count"
              interval    = "86400000"
              metric      = "count"
            }

            data_source = "rum"
            indexes     = ["*"]
            name        = "a"

            search {
              query = "@type:session @application.id:3b19a7c7-f03e-4c05-a83b-3b65d2ed489a @session.type:user"
            }

            storage = "hot"
          }
        }

        style {
          palette = "dog_classic"
        }
      }

      show_legend = "false"
      title       = "Number of Sessions by Day"
      title_align = "left"
      title_size  = "16"
    }

    widget_layout {
      height          = "4"
      is_column_break = "false"
      width           = "6"
      x               = "0"
      y               = "4"
    }
  }
}
