project_name: b3tr-frontend
project_slug: governance-frontend
environment: prod
region: eu-west-1
account_id: "851725442887"

account_level_state_region: eu-west-1

domain: governance.vebetterdao.org
enable_custom_domain: true
route53_zone_name: governance.vebetterdao.org

ssm_parameter_prefix: /b3tr/frontend/
runtime_env_var_names:
  - FRESHDESK_DOMAIN
  - FRESHDESK_GROUP_ID
  - GITHUB_CLIENT_ID
  - RESET_USER_SIGNAL_COUNT_DOMAIN
  - TWITTER_CLIENT_ID
  - NEXTAUTH_URL

runtime_env_secret_names:
  - FRESHDESK_API_TOKEN
  - GITHUB_CLIENT_SECRET
  - MNEMONIC
  - NEXTAUTH_SECRET
  - RESET_USER_SIGNAL_COUNT_API_KEY
  - TWITTER_CLIENT_SECRET

image_tag: latest
cpu: 1024
memory: 2048
port: 3000
min_size: 1
max_size: 4
max_concurrency: 100
health_check_path: /
health_check_interval: 20
health_check_timeout: 10
health_check_healthy_threshold: 1
health_check_unhealthy_threshold: 3
node_env: production
auto_deployments_enabled: false
