---
# AWS Configuration
aws_region: eu-west-1
aws_account_id: "211125319139"
environment: "testnet"

# Lambda Configuration
lambda_function_name: "finalize-challenges"
lambda_handler: "index.handler"
lambda_runtime: "nodejs20.x"
lambda_memory_size: 512
lambda_timeout: 900

# Lambda Build Path
lambda_source_dir: "packages/lambda/dist/testnet-staging/finalizeChallenges"

# Schedule Configuration
# Runs 10 minutes after start-emissions-round
schedule_expression: "cron(40 1 ? * TUE,THU,SAT *)"
