import { useMemo } from "react"
import { useTranslation } from "react-i18next"

import { InfoStep, InfoStepsCard } from "@/components/InfoStepsCard"

export const NavigatorStepsCard = ({ isOpen, onClose }: { isOpen: boolean; onClose: () => void }) => {
  const { t } = useTranslation()

  const steps = useMemo<InfoStep[]>(
    () => [
      {
        key: "what",
        title: t("Navigators"),
        image: "/assets/mascot/navigator-b3mo.png",
        imageDimensions: {
          width: { base: "180px", md: "280px" },
          height: { base: "180px", md: "280px" },
        },
        heading: t("1. What are Navigators?"),
        listItems: [
          t(
            "Navigators are engaged community members who help steer the ecosystem. They stake B3TR, publish their allocation rationale each round, and earn 20% of B3TR rewards from votes they manage.",
          ),
          t(
            "They vote allocation rounds and governance on behalf of citizens who delegate VOT3 to them—with public accountability and skin in the game.",
          ),
        ],
      },
      {
        key: "delegate",
        title: t("Citizens & delegation"),
        image: "/assets/3d-illustrations/voting-power-hr.png",
        heading: t("2. Delegate your VOT3"),
        listItems: [
          t(
            "As a citizen, you hold VOT3 and can delegate part of it to a Navigator you trust. Pick a Navigator and choose how much to delegate. Your tokens stay in your wallet—only the delegated portion is locked.",
          ),
          t(
            "Compare strategies and track records. Different Navigators emphasize different priorities—wellbeing, rewards, thematic focus, and more—so you can follow the rationale that fits you. You can switch anytime.",
          ),
        ],
      },
      {
        key: "earn",
        title: t("Voting & rewards"),
        image: "/assets/images/grants/step-4.webp",
        heading: t("3. Curated votes, not lazy repeats"),
        listItems: [
          t(
            "Your Navigator votes allocation rounds and governance for you—similar convenience to auto-voting, but with intentional picks. They can adjust for news and ecosystem developments so delegations stay considered, not on autopilot.",
          ),
          t(
            "Your rewards scale with your delegated amount. A 20% Navigator fee is deducted automatically from the rewards generated by votes they manage.",
          ),
        ],
      },
      {
        key: "manage",
        title: t("Control & accountability"),
        image: "/assets/images/grants/step-3.webp",
        heading: t("4. Stay in control"),
        listItems: [
          t("You can undelegate fully or partially at any time."),
          t("If a Navigator exits or is deactivated, your VOT3 is automatically unlocked—no action needed."),
          t(
            "If a Navigator neglects their duties, anyone can report round infractions on-chain. Valid reports slash part of their staked B3TR—keeping the role accountable.",
          ),
        ],
      },
    ],
    [t],
  )

  return <InfoStepsCard steps={steps} isOpen={isOpen} onClose={onClose} />
}
