project_name: b3tr-frontend
project_slug: governance-frontend
environment: prod
region: eu-west-1
account_id: "851725442887"

hosted_zone_name: governance.vebetterdao.org

# Optional role to assume when running Terraform (leave blank to use caller credentials)
# assume_role_arn: "arn:aws:iam::851725442887:role/terraform-deployer"

ecr_repository_name: governance-frontend
