export type ContractsConfig = {
  NEXT_PUBLIC_APP_ENV: "local" | "solo-staging" | "testnet" | "production"

  B3TR_CAP: number
  B3TR_GOVERNOR_QUORUM_PERCENTAGE: number
  B3TR_GOVERNOR_MIN_DELAY: number
  B3TR_GOVERNOR_VOTING_PERIOD: number
  B3TR_GOVERNOR_VOTING_DELAY: number
  B3TR_GOVERNOR_PROPOSAL_THRESHOLD: number

  EMISSIONS_CYCLE_DURATION: number
  EMISSIONS_X_ALLOCATION_DECAY_PERCENTAGE: number
  EMISSIONS_VOTE_2_EARN_DECAY_PERCENTAGE: number
  EMISSIONS_X_ALLOCATION_DECAY_PERIOD: number
  EMISSIONS_VOTE_2_EARN_ALLOCATION_DECAY_PERIOD: number
  EMISSIONS_TREASURY_PERCENTAGE: number
  EMISSIONS_MAX_VOTE_2_EARN_DECAY_PERCENTAGE: number

  X_ALLOCATION_VOTING_QUORUM_PERCENTAGE: number

  X_ALLOCATION_POOL_BASE_ALLOCATION_PERCENTAGE: number
  X_ALLOCATION_POOL_APP_SHARES_MAX_CAP: number

  CONTRACTS_ADMIN_ADDRESS: string

  VOTE_2_EARN_POOL_ADDRESS: string

  INITIAL_X_ALLOCATION: bigint

  NFT_BADGE_BASE_URI: string
  NFT_BADGE_X_NODE_UPGRADEABLE_LEVELS: number[]
  NFT_BADGE_B3TR_REQUIRED_TO_UPGRADE_TO_LEVEL: bigint[]

  VOTER_REWARDS_LEVELS: number[],
  VOTER_REWARDS_MULTIPLIER: number[],

  XAPP_BASE_URI: string
}
