export * from "./animation"
export * from "./contractList"
export * from "./GovernanceFeaturedFunctions"
export * from "./GovernanceProposalTemplate"
export * from "./links"
export * from "./url"
export * from "./animation"
export * from "./Passport"
export * from "./transactions"
export * from "./AnalyticsEvents"
export * from "./featureFlag"
export * from "./XAppsMedia"
export * from "./proposals"

export const notFoundImage = "/assets/images/image-not-found.webp"
