#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

yarn lint-staged

./apps/frontend/scripts/check-unused-assets.sh
chmod +x ./apps/frontend/scripts/check-logs.sh
./apps/frontend/scripts/check-logs.sh
