name: Chromatic

on:
  pull_request_target:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    if: "!startsWith(github.head_ref, 'release/')"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Use Node v20
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: "yarn"

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            apps/*/node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: apps/frontend
          buildScriptName: build-storybook
          exitZeroOnChanges: false
          autoAcceptChanges: "main"
          onlyStoryNames: "apps/frontend/src/stories/**"
          zip: true
          autoAcceptChanges: "main"
        env:
          NEXT_PUBLIC_APP_ENV: staging
