name: Codebase Versioning

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  semantic-versioning:
    uses: vechain/github-actions-public/.github/workflows/semantic-versioning.yaml@b3ab84727d2c8fe86a6a7ce6963c82486afbaa49 # v.2.1.1
    secrets:
      DEPLOY_KEY: ${{ secrets.VECHAINCI_SSH_PRIVATE_KEYS }}
