# Deploy Storybook when PR with relevant changes is merged to main
name: Deploy Storybook

on:
  push:
    branches:
      - main
    paths:
      - "apps/frontend/**"
      - "packages/**"
      - ".github/workflows/deploy-storybook.yml"
      - ".github/workflows/deploy-storybook-main.yml"

jobs:
  deploy:
    uses: ./.github/workflows/deploy-storybook.yml
    secrets: inherit

