# Deploy to Staging and Beta when a version tag is pushed
name: Deploy Frontend - Staging & Beta

on:
  push:
    tags:
      - 'v.*'

jobs:
  deploy:
    name: Deploy to ${{ matrix.environment }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - environment: staging
            image_tag: staging-${{ github.ref_name }}
          - environment: beta
            image_tag: beta-${{ github.ref_name }}
    uses: ./.github/workflows/deploy-fe.yml
    secrets: inherit
    with:
      environment: ${{ matrix.environment }}
      image_tag: ${{ matrix.image_tag }}
