name: Start next Round Testnet

on:
  workflow_dispatch:
  schedule:
    # Runs at 23:59 UTC every Sunday
    - cron: '59 23 * * 0'

jobs:
  start-next-round:
    name: Start next Round Testnet
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Use Node v20
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: 20
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Start round Testnet
        run: yarn contracts:start-round:testnet     
        timeout-minutes: 30

   