name: Main Merge - Publish Images & Deploy Dead Color (if exists)

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  publish-images-to-ecr:
    name: Build Images & Publish to ECR
    secrets: inherit
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        env: [dev]
        application: [ thor-solo ]
    uses: ./.github/workflows/publish-ecr-image.yml
    with:
      latestTag: ${{ matrix.env }}-latest
      imageTag: ${{ github.sha }}
      buildArgs: |
        THOR_SOLO_PACKAGE=${{ matrix.application }}
      workingDirectory: ./
      packageName: ${{ matrix.application }}
      imagePlatform: linux/arm64
      env: ${{ matrix.env }}
