name: Playwright E2E

on:
  push:
    branches:
      - feat/e2e

jobs:
    run-e2e-tests:
        name: E2E Tests
        runs-on: ubuntu-latest
    
        steps:
          - name: Checkout repository
            uses: actions/checkout@v3
    
          - name: Use Node v20
            uses: actions/setup-node@v3
            with:
              node-version: 20
              cache: "yarn"

          - name: Install dependencies
            run: yarn install --frozen-lockfile

          - name: Launch solo
            run: yarn solo-up
        
          - name: Launch app
            run: yarn dev &
        
          - name: Health check
            run: |
                cd packages/e2e
                chmod +x health-check.sh
                yarn dev:health-check

          - name: Run tests
            run: |
                cd packages/e2e
                yarn playwright:e2e