name: Deploy to GH pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  packages: write

jobs:
  BuildAndDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Repo Deps
        run: yarn

      - name: Generate Solo Config
        run: cp ./packages/config/solo-staging.ts ./packages/config/local.ts

      - name: Generate Contract Artifacts
        working-directory: ./packages/contracts
        run: yarn hardhat compile
        env:
          MNEMONIC: denial kitchen pet squirrel other broom bar gas better priority spoil cross

      - name: Debug
        run:  find packages/contracts/artifacts/contracts -type f -name '*.json'

      - name: Cleane Dependency FILE
        run: sed -i '1d' packages/constants/network/network.ts

      - name: Install Inspector Deps
        working-directory: ./inspector-app
        run: yarn

      - name: Build Website
        working-directory: ./inspector-app
        run: |
          nohup yarn build &
          sleep 60

      - name: Debug
        run: ls -la ./inspector-app/dist

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './inspector-app/dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

