name: 'Security Checks'
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  scorecard:
    uses: vechain/github-actions/.github/workflows/scorecard.yaml@f49d46852ef14c1e0cb46a49175c0fe897f4018c # v.1.4.0
    secrets:
      app-id: ${{ secrets.SCORECARD_APPID }}
      private-key: ${{ secrets.SCORECARD_PRIVATEKEY }}
  checkov:
      uses: vechain/github-actions/.github/workflows/checkov.yaml@f49d46852ef14c1e0cb46a49175c0fe897f4018c # v.1.4.0
  infracost:
    uses: vechain/github-actions/.github/workflows/infracost.yaml@7afcb88e42aa6ab0636dd5d899f9bb5cf2806cf1 # v.1.5.0
    secrets:
      INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
      GIT_VECHAINCI_SSH_KEY: ${{ secrets.VECHAINCI_SSH_PRIVATE_KEYS }}
  sonar-scan:
    uses: vechain/github-actions/.github/workflows/sonar-scan.yaml@ceb183bdac66f0a97f51bd1318a17c027b2bfa07 # v.1.7.0
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    with:
      download-coverage-report: false
