name: Slither

on:
  workflow_dispatch:

jobs:
  run-slither:
    name: Slither Analysis
    uses: vechain/github-actions-public/.github/workflows/slither.yaml@f54f69d33344b241b5ec901d3d5e1b02d44a1b96 # v.2.3.0
    with:
      solc-version: "0.8.20"
      target: "packages/contracts/"
      fail-on: "none"
      cache: "yarn"
      compile-command: "yarn contracts:compile:slither"
      ignore-compile: true
      slither-args: |
        --filter-paths "(openzeppelin|mocks|interfaces|deprecated|templates)" --exclude-informational --exclude-optimization --checklist --markdown-root ${{ github.server_url }}/${{ github.repository }}/blob/${{ github.sha }}/
