#name: Slither

#on:
  # push:
  #   branches:
  #     - main
  #     - add-slither
  # pull_request:

# jobs:
#   slither:
#         uses: vechain/github-actions/.github/workflows/slither.yaml@feature/waqar/add-falsepositive-slither  #v1.10.0
#         with:
#           solc-version: '0.8.20'
#           target: 'packages/contracts/'
#           fail-on: 'none'
#           cache: 'yarn'
# #          compile-command: 'yarn contracts:compile'
#           ignore-compile: true
#           slither-args: |
#             --filter-paths "(openzeppelin|mocks|interfaces|deprecated|templates)" --config-file slither.config.json --checklist --json slither.raw.json --markdown-root ${{ github.server_url }}/${{ github.repository }}/blob/${{ github.sha }}/
# #           --filter-paths "(openzeppelin|mocks|interfaces|deprecated|templates)" --exclude-informational --exclude-optimization --checklist --markdown-root ${{ github.server_url }}/${{ github.repository }}/blob/${{ github.sha }}/
