name: Smart Contract Testing

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - testnet
      - gm-and-endorsements
  push:
    branches:
      - main
      - testnet

jobs:
  utils-changes:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.filter.outputs.src }}
    steps:
      - name: Check for Utils changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            src:
              - 'packages/utils/**'

  contract-changes:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.filter.outputs.src }}
    steps:
      - name: Check for Solidity changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            src:
              - 'packages/contracts/**'

  solidity-tests:
    runs-on: ubuntu-latest
    needs: [contract-changes, utils-changes]
    if: needs.contract-changes.outputs.changes == 'true' || needs.utils-changes.outputs.changes == 'true'
    strategy:
      fail-fast: false
      matrix:
        shard: [shard1, shard2]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node v20
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Cache Solidity compilers
        uses: actions/cache@v3
        with:
          path: ~/.cache/hardhat-nodejs
          key: ${{ runner.os }}-solc-${{ hashFiles('./packages/contracts/hardhat.config.ts') }}
          restore-keys: |
            ${{ runner.os }}-solc-

      - name: Run Unit Tests for ${{ matrix.shard }}
        run: SHARD='@${{ matrix.shard }}' yarn contracts:test:shard
