name: Unit Test Coverage

on:
  workflow_dispatch:

jobs:
  run-coverage:
    name: Unit tests coverage
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Use Node v20
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: .nvmrc
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run FE coverage
        id: fe-coverage
        run: yarn test:coverage:fe

      - name: Archive FE coverage
        if: steps.fe-coverage.outcome == 'success'
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: fe-coverage
          path: apps/frontend/coverage
          retention-days: 10
