name: Unit Test Coverage

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      run_fe:
        required: false
        type: boolean
        default: true
      run_solidity:
        required: false
        type: boolean
        default: true

jobs:
  run-coverage:
    name: Unit tests coverage
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node v20
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run FE coverage
        if: ${{ github.event.inputs.run_fe }}
        id: fe-coverage
        run: yarn test:coverage:fe

      - name: Archive FE coverage
        if: steps.fe-coverage.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: fe-coverage
          path: apps/frontend/coverage
          retention-days: 10

      - name: Run solidity coverage
        if: ${{ github.event.inputs.run_solidity }}
        id: contract-coverage
        run: yarn test:coverage:solidity

      - name: Archive solidity coverage
        if: steps.contract-coverage.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: solidity-coverage
          path: packages/contracts/coverage
          retention-days: 10
