name: Unit Testing

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  run-unit-tests:
    name: Unit Testing
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node v20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "yarn"

      - name: Configure npm for private package
        run: |
          echo "@vechain:registry=https://npm.pkg.github.com/" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_READ_PACKAGES_TOKEN }}" >> .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Unit Tests
        run: yarn test
      
      - name: Slither human summary
        uses: crytic/slither-action@v0.3.1
        id: slitherhumansummary
        with:
          ignore-compile: true
          target: 'packages/contracts/'
          solc-version: '0.8.20'
          fail-on: none
          slither-args: --print human-summary
          
      - name: Run Slither
        uses: crytic/slither-action@v0.3.1
        id: slither
        with:
          ignore-compile: true
          target: 'packages/contracts/'
          solc-version: '0.8.20'
          fail-on: none
          slither-args: --checklist --markdown-root ${{ github.server_url }}/${{ github.repository }}/blob/${{ github.sha }}/
      
     # - uses: actions/upload-artifact@v4
     #   with:
     #     name: my-artifact
     #     path: ${{ steps.slither.outputs.stdout }}
    
      - name: Create/update checklist as PR comment
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        env:
          REPORT: ${{ steps.slither.outputs.stdout }}
          #REPORT: 'THis is a test report with some tags <h1>Hello</h1>'
        with:
          script: |
            const script = require('.github/scripts/comment')
            const header = '# Slither report'
            const body = 'This is a test report with some tags <h1>Hello</h1>'
            await script({ github, context, header, body })
      
