name: Unit Testing

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - testnet
      - dan/ve-better-passport
  push:
    branches:
      - main
      - Comment-only-solidity-changes
      - testnet

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      frontend-changed: ${{ steps.changes.outputs.frontend }}
      contracts-changed: ${{ steps.changes.outputs.contracts }}
      utils-changed: ${{ steps.changes.outputs.utils }}
      backend-changed: ${{ steps.changes.outputs.backend }}
      lambda-changed: ${{ steps.changes.outputs.lambda }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check for Changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            frontend:
              - 'apps/frontend/**'
            contracts:
              - 'packages/contracts/**'
            utils:
              - 'packages/utils/**'
            backend:
              - 'apps/backend/**'
            lambda:
              - 'packages/lambda/**'

  run-unit-tests:
    name: Unit Testing
    runs-on: ubuntu-latest
    needs: check-changes
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node v20
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Cache Solidity compilers
        uses: actions/cache@v3
        with:
          path: ~/.cache/hardhat-nodejs
          key: ${{ runner.os }}-solc-${{ hashFiles('./packages/contracts/hardhat.config.ts') }}
          restore-keys: |
            ${{ runner.os }}-solc-

      # Run global unit tests if contract or utils changes are detected
      - name: Global Unit Tests
        if: needs.check-changes.outputs.contracts-changed == 'true' || needs.check-changes.outputs.utils-changed == 'true'
        run: yarn test

      # Run Frontend unit tests if there are frontend changes, or if contracts/utils have changed
      - name: Frontend Unit Tests
        if: needs.check-changes.outputs.frontend-changed == 'true' || needs.check-changes.outputs.contracts-changed == 'true' || needs.check-changes.outputs.utils-changed == 'true'
        run: yarn test --filter=frontend

      # Run Backend unit tests only if there are backend changes and no contracts/utils changes
      - name: Backend Unit Tests
        if: needs.check-changes.outputs.backend-changed == 'true' && needs.check-changes.outputs.contracts-changed != 'true' && needs.check-changes.outputs.utils-changed != 'true'
        run: yarn test --filter=backend

      # Run Lambda unit tests only if there are lambda changes and no contracts/utils changes
      - name: Lambda Unit Tests
        if: needs.check-changes.outputs.lambda-changed == 'true' && needs.check-changes.outputs.contracts-changed != 'true' && needs.check-changes.outputs.utils-changed != 'true'
        run: yarn test --filter=lambda

  run-contract-tests:
    name: Contract Testing
    runs-on: ubuntu-latest
    needs: check-changes
    if: needs.check-changes.outputs.contracts-changed == 'true'
    strategy:
      fail-fast: false
      matrix:
        shard: [shard1, shard2, shard3]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node v20
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Cache Solidity compilers
        uses: actions/cache@v3
        with:
          path: ~/.cache/hardhat-nodejs
          key: ${{ runner.os }}-solc-${{ hashFiles('./packages/contracts/hardhat.config.ts') }}
          restore-keys: |
            ${{ runner.os }}-solc-

      - name: Run Contract Tests for ${{ matrix.shard }}
        run: SHARD='@${{ matrix.shard }}' yarn contracts:test:shard