name: Validate PR Label
on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, labeled, unlabeled, synchronize]
  workflow_dispatch:

jobs:
  validate:
    uses: vechain/github-actions/.github/workflows/validate-pr-label.yaml@3cd16b776655eeeb18f22c820ec5f79aca0f437d # v.1.13.2
    with:
      FAIL_IF_MISSING_LABEL: true
