name: Validate PR Label
on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, labeled, unlabeled, synchronize]
  workflow_dispatch:

jobs:
  validate:
    uses: vechain/github-actions/.github/workflows/validate-pr-label.yaml@eb785b483c03bb4596f67828d659f0a1fabeb72f # v.1.15.0
    with:
      FAIL_IF_MISSING_LABEL: true
