name: VeBetterPassport Infrastructure

on:
  push:
    branches:
      - terraformer-import
    paths:
      - 'terraform/vebetterpassport/**'
      - 'lambda/src/veBetterPassport/**'
      - '.github/workflows/vebetterpassport.yml'
  workflow_dispatch:
    inputs:
      workspace:
        description: 'Terraform workspace to use (dev, prod)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

permissions:
  id-token: write
  contents: read
  pull-requests: read

jobs:
  vebetterpassport-plan:
    name: VeBetterPassport Plan
    runs-on: ubuntu-latest
    outputs:
      plan_changes_detected: ${{ steps.check_changes.outputs.plan_changes_detected }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ github.event.inputs.workspace == 'prod' && secrets.AWS_ACCESS_ROLE || secrets.DEV_AWS_ACC_ROLE }}
          aws-region: eu-west-1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: |
          echo "Installing project dependencies..."
          yarn install
          echo "Installing esbuild globally..."
          yarn global add esbuild
          echo "Verify esbuild installation..."
          esbuild --version

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.3
    
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.VECHAINCI_SSH_PRIVATE_KEYS }}

      - name: Configure Secret Masking
        run: |
          echo "::add-mask::${{ secrets.MAINNET_MNEMONIC }}"
          # Add any parts of the mnemonic that might appear in logs
          IFS=' ' read -ra WORDS <<< "${{ secrets.MAINNET_MNEMONIC }}"
          for i in "${WORDS[@]}"; do
            echo "::add-mask::$i"
          done

      - name: Terraform Format
        id: fmt
        working-directory: terraform/vebetterpassport
        run: terraform fmt -check -recursive
        continue-on-error: true

      - name: Terraform Init
        working-directory: terraform/vebetterpassport
        run: terraform init

      - name: Terraform Workspace
        working-directory: terraform/vebetterpassport
        id: workspace
        run: |
          WORKSPACE="${{ github.event_name == 'workflow_dispatch' && github.event.inputs.workspace || 'dev' }}"
          
          if ! terraform workspace list | grep -q "$WORKSPACE"; then
            terraform workspace new "$WORKSPACE"
          else
            terraform workspace select "$WORKSPACE"
          fi
    
      - name: Terraform Validate
        working-directory: terraform/vebetterpassport
        id: validate
        run: terraform validate

      - name: Terraform Plan
        working-directory: terraform/vebetterpassport
        id: plan
        env:
          MAINNET_MNEMONIC: ${{ secrets.TEST_MNEMONIC }}
          TF_LOG: ERROR # Limit Terraform logging to reduce chance of secrets exposure
        run: terraform plan -out=vebetterpassport.tfplan -detailed-exitcode
    
      - name: Check for plan changes
        id: check_changes
        run: |
          if [ ${{ steps.plan.outcome }} == 'success' ] && [ ${{ steps.plan.outputs.exitcode }} == 2 ]; then
            echo "Changes detected"
            echo "plan_changes_detected=true" >> $GITHUB_OUTPUT
          else
            echo "No changes detected"
            echo "plan_changes_detected=false" >> $GITHUB_OUTPUT
          fi
        shell: bash
        continue-on-error: false

      - name: Upload Plan
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: vebetterpassport-plan
          path: terraform/vebetterpassport/vebetterpassport.tfplan
          retention-days: 5
      
      - name: Terraform Apply
        working-directory: terraform/vebetterpassport
        env:
          MAINNET_MNEMONIC: ${{ secrets.MAINNET_MNEMONIC }}
          TF_LOG: ERROR # Limit Terraform logging to reduce chance of secrets exposure
        run: terraform apply -auto-approve vebetterpassport.tfplan
