name: VeBetterPassport Lambda Deployment

on:
  pull_request:
    paths:
      - 'terraform/vebetterpassport/**'
      - 'lambda/src/vebetterpassport/**'
      - '.github/workflows/vebetterpassport-lambda-deploy.yml'
  workflow_dispatch:
    inputs:
      workspace:
        description: 'Terraform workspace to use (dev, prod)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

permissions:
  id-token: write
  contents: read
  pull-requests: read

jobs:
  build:
    name: Build Lambda
    uses: ./.github/workflows/lambda-build.yml
    with:
      workspace: ${{ github.event.inputs.workspace || 'dev' }}
    secrets:
      TESTNET_MNEMONIC: ${{ secrets.TESTNET_MNEMONIC }}
      MAINNET_MNEMONIC: ${{ secrets.MAINNET_MNEMONIC }}

  deploy:
    name: Deploy Infrastructure
    needs: build
    uses: ./.github/workflows/lambda-infrastructure-deploy.yml
    with:
      workspace: ${{ github.event.inputs.workspace || 'dev' }}
      lambda_name: vebetterpassport
      terraform_dir: terraform/vebetterpassport
    secrets:
      AWS_ACCESS_ROLE: ${{ secrets.AWS_ACCESS_ROLE }}
      DEV_AWS_ACC_ROLE: ${{ secrets.DEV_AWS_ACC_ROLE }}
      VECHAINCI_SSH_PRIVATE_KEYS: ${{ secrets.VECHAINCI_SSH_PRIVATE_KEYS }}